# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71d83db4bdf3c41e3e1e059d844f0f4cc0de141845503e0f720f1c6e05936381a7dfd5de4022856211f0d884ed396bf99b18c521b861f3f014eb74697d2e17b2

test:
  secret_key_base: e62d04ef75534e6112de7343ab9698abba7ad008cd4b2557efd38a05807029579b9ee1af8b14dc224be8bd25226ae57327905abaa327a2985f1f52d2bb29ad3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
